CREATE TABLE IF NOT EXISTS usuario(
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(60) NOT NULL,
  sobrenome VARCHAR(120) NOT NULL,
  email VARCHAR(120) UNIQUE NOT NULL,
  senha VARCHAR(120) NOT NULL,
  telefone VARCHAR(20) NOT NULL,  
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS contatos(
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(60) NOT NULL,
  sobrenome VARCHAR(120) NOT NULL,
  apelido VARCHAR(30) UNIQUE NOT NULL,
  cidade VARCHAR(30) NOT NULL,
  aniversario VARCHAR(12),
  email VARCHAR(120) UNIQUE NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  usuario_id INTEGER,
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

